// packages/svelte/src/Toolbar/Toolbar.svelte
<script lang="ts">
import type { Component } from 'svelte'
import { useCalendarContext } from '../CalendarProvider'
import DefaultToolbar from '../DefaultToolbar/DefaultToolbar.svelte'
import { useToolbarProps } from '../useToolbarProps'

const { components } = useCalendarContext()
const ToolbarComp = (components.toolbar ?? DefaultToolbar) as Component
const toolbarProps = useToolbarProps()
</script>

<svelte:component this={ToolbarComp} {...toolbarProps.current} />

// packages/vue/src/Toolbar/Toolbar.vue
<script setup lang="ts">
import type { Component } from 'vue'
import { useCalendarContext } from '../CalendarProvider'
import DefaultToolbar from '../DefaultToolbar/DefaultToolbar.vue'
import { useToolbarProps } from '../useToolbarProps/useToolbarProps'

const { components } = useCalendarContext()
const ToolbarComp = (components.toolbar ?? DefaultToolbar) as Component
const toolbarProps = useToolbarProps()
</script>

<template>
  <component :is="ToolbarComp" v-bind="toolbarProps" />
</template>
