// packages/vue/src/DefaultToolbar/DefaultToolbar.vue
<script setup lang="ts">
import type { NavigateDirection, ViewKey } from '@big-calendar/core'
import { BUILTIN_VIEWS, Navigate } from '@big-calendar/core'
import type { Messages } from '@big-calendar/core'

const props = defineProps<{
  label: string
  view: ViewKey
  views: ViewKey[]
  messages: Messages
  onNavigate: (direction: NavigateDirection) => void
  onView: (view: ViewKey) => void
}>()

const BUILTIN = new Set<string>(BUILTIN_VIEWS)

function viewButtonLabel(key: ViewKey): string {
  return BUILTIN.has(key) ? (props.messages[key as keyof Messages] as string) ?? key : key
}
</script>

<template>
  <div class="bc-toolbar">
    <div class="bc-toolbar-group">
      <button type="button" @click="onNavigate(Navigate.PREVIOUS)">
        {{ messages.previous }}
      </button>
      <button type="button" @click="onNavigate(Navigate.TODAY)">
        {{ messages.today }}
      </button>
      <button type="button" @click="onNavigate(Navigate.NEXT)">
        {{ messages.next }}
      </button>
    </div>
    <span class="bc-toolbar-label">{{ label }}</span>
    <div class="bc-toolbar-group">
      <button
        v-for="option in views"
        :key="option"
        type="button"
        :aria-pressed="option === view"
        @click="onView(option)"
      >
        {{ viewButtonLabel(option) }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/DefaultToolbar/DefaultToolbar.component.tsx
import { BUILTIN_VIEWS, Navigate } from '@big-calendar/core'
import type { BuiltinViewKey, Messages, ViewKey } from '@big-calendar/core'
import type { ToolbarProps } from '../components.type'

const BUILTIN = new Set<string>(BUILTIN_VIEWS)

/** A view's switcher label: the localized message for a built-in, else the raw key. */
function viewButtonLabel(messages: Messages, view: ViewKey): string {
  return BUILTIN.has(view) ? messages[view as BuiltinViewKey] : view
}

/**
 * Default navigation toolbar: a today / prev / next group, the localized view
 * label, and a view switcher. Replace it wholesale via `components.toolbar`.
 * Attaches only `@big-calendar/styles` class names — it ships no CSS.
 */
function DefaultToolbar({ label, view, views, messages, onNavigate, onView }: ToolbarProps) {
  return (
    <div className="bc-toolbar">
      <div className="bc-toolbar-group">
        <button type="button" aria-label={messages.previous} onClick={() => onNavigate(Navigate.PREVIOUS)}>
          ‹
        </button>
        <button type="button" aria-label={messages.today} onClick={() => onNavigate(Navigate.TODAY)}>
          ·
        </button>
        <button type="button" aria-label={messages.next} onClick={() => onNavigate(Navigate.NEXT)}>
          ›
        </button>
      </div>
      <span className="bc-toolbar-label">{label}</span>
      <div className="bc-toolbar-group">
        {views.map((option) => (
          <button
            key={option}
            type="button"
            aria-pressed={option === view}
            onClick={() => onView(option)}
          >
            {viewButtonLabel(messages, option)}
          </button>
        ))}
      </div>
    </div>
  )
}

export default DefaultToolbar
