// packages/react/src/Toolbar/Toolbar.component.tsx
import { useCalendarContext } from '../CalendarProvider'
import DefaultToolbar from '../DefaultToolbar'
import { useToolbarProps } from '../useToolbarProps'

/**
 * The calendar navigation toolbar. Resolves its props from context and renders
 * either the `components.toolbar` override or the built-in {@link DefaultToolbar}.
 * Must render inside a {@link CalendarProvider}.
 */
function Toolbar() {
  const { components } = useCalendarContext()
  const props = useToolbarProps()
  const Component = components.toolbar ?? DefaultToolbar
  return <Component {...props} />
}

export default Toolbar

// packages/svelte/src/Toolbar/Toolbar.svelte
<script lang="ts">
import type { Component } from 'svelte'
import { useCalendarContext } from '../CalendarProvider'
import DefaultToolbar from '../DefaultToolbar/DefaultToolbar.svelte'
import { useToolbarProps } from '../useToolbarProps'

const { components } = useCalendarContext()
const ToolbarComp = (components.toolbar ?? DefaultToolbar) as Component
const toolbarProps = useToolbarProps()
</script>

<svelte:component this={ToolbarComp} {...toolbarProps.current} />
