// packages/vue/src/EventButton/EventButton.vue
<script setup lang="ts" generic="TEvent = unknown">
import { wrapAccessor } from '@big-calendar/core'
import type { ResizeEdge } from '@big-calendar/core'
import clsx from 'clsx'
import { computed, onUnmounted, ref } from 'vue'
import { useCalendarContext } from '../CalendarProvider'
import { useSignalRef } from '../internal/useSignalRef'

const DOUBLE_CLICK_MS = 250

const props = defineProps<{
  event: TEvent
  title: string
  time?: string | undefined
  class: string
  style?: Record<string, string> | undefined
  resizeEdges?: readonly ResizeEdge[] | undefined
}>()

const { store, descriptionIds } = useCalendarContext<TEvent>()
const { eventHandlers } = store

const idAccessor = wrapAccessor(store.accessors.id)
const id = computed(() => idAccessor(props.event))

const selectedRef = useSignalRef(store.selected)
const grabRef = useSignalRef(store.keyboardDrag)
const dndRef = useSignalRef(store.dndEnabled)

const isSelected = computed(() => id.value != null && selectedRef.value === id.value)
const isGrabbed = computed(() => id.value != null && grabRef.value != null && String(grabRef.value.id) === String(id.value))
const isDraggable = computed(() => dndRef.value && store.isDraggable(props.event))
const edges = computed<readonly ResizeEdge[]>(() =>
  props.resizeEdges != null && dndRef.value && store.isResizable(props.event)
    ? props.resizeEdges
    : [],
)

const buttonClass = computed(() =>
  clsx(props.class, isGrabbed.value && 'bc-event-grabbed', isDraggable.value && 'bc-event-draggable'),
)

const accessibleName = computed(() =>
  props.time ? `${props.title}, ${props.time}` : props.title,
)

const clickTimer = ref<ReturnType<typeof setTimeout> | null>(null)
onUnmounted(() => {
  if (clickTimer.value !== null) clearTimeout(clickTimer.value)
})

const select = () => {
  const evId = id.value
  if (evId != null) store.selectEvent({ id: evId })
}
const primary = () => {
  select()
  eventHandlers.click(props.event)
}
const secondary = () => {
  select()
  eventHandlers.doubleClick(props.event)
}

function handleClick(e: MouseEvent) {
  if (e.detail === 0) return
  if (clickTimer.value !== null) return
  clickTimer.value = setTimeout(() => {
    clickTimer.value = null
    primary()
  }, DOUBLE_CLICK_MS)
}

function handleDblClick() {
  if (clickTimer.value !== null) {
    clearTimeout(clickTimer.value)
    clickTimer.value = null
  }
  secondary()
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault()
    primary()
  } else if (e.key === 'F2') {
    e.preventDefault()
    secondary()
  }
}

function handleContextmenu(e: MouseEvent) {
  if (eventHandlers.hasRightClick) eventHandlers.rightClick(props.event, e)
}

function handleAuxclick(e: MouseEvent) {
  if (e.button === 1 && eventHandlers.hasMiddleClick) {
    eventHandlers.middleClick(props.event, e)
  }
}

function handlePointerdown(e: PointerEvent) {
  e.stopPropagation()
}
</script>

<template>
  <button
    type="button"
    :class="buttonClass"
    :style="style"
    :data-bc-event="id == null ? '' : String(id)"
    :aria-selected="isSelected"
    :aria-grabbed="isGrabbed || undefined"
    :aria-label="accessibleName || undefined"
    aria-keyshortcuts="Enter Space F2"
    :aria-describedby="descriptionIds.event"
    @click="handleClick"
    @dblclick="handleDblClick"
    @keydown="handleKeydown"
    @contextmenu="eventHandlers.hasRightClick ? handleContextmenu($event) : undefined"
    @auxclick="eventHandlers.hasMiddleClick ? handleAuxclick($event) : undefined"
    @pointerdown="handlePointerdown"
  >
    <slot />
    <span
      v-for="edge in edges"
      :key="edge"
      :class="`bc-resize-handle bc-resize-handle-${edge}`"
      :data-bc-resize="edge"
      aria-hidden="true"
    />
  </button>
</template>

// packages/svelte/src/EventButton/EventButton.svelte
<script lang="ts" generics="TEvent = unknown">
import type { Snippet } from 'svelte'
import { onDestroy } from 'svelte'
import type { ResizeEdge } from '@big-calendar/core'
import { wrapAccessor } from '@big-calendar/core'
import clsx from 'clsx'
import { useCalendarContext } from '../CalendarProvider'
import { fromSignal } from '../internal/fromSignal.svelte'

const DOUBLE_CLICK_MS = 250

let {
  event,
  title,
  time,
  class: extraClass = '',
  style,
  resizeEdges,
  children,
}: {
  event: TEvent
  title: string
  time?: string
  class?: string
  style?: string
  resizeEdges?: readonly ResizeEdge[]
  children?: Snippet
} = $props()

const { store, descriptionIds } = useCalendarContext<TEvent>()
const { eventHandlers } = store
const idAccessor = wrapAccessor(store.accessors.id)

const id = $derived(idAccessor(event))

const selected = fromSignal(store.selected)
const grabbed = fromSignal(store.keyboardDrag)
const dnd = fromSignal(store.dndEnabled)

const isSelected = $derived(id != null && selected.current === id)
const isGrabbed = $derived(id != null && grabbed.current != null && String(grabbed.current.id) === String(id))
const isDraggable = $derived(dnd.current && store.isDraggable(event))
const edges = $derived<readonly ResizeEdge[]>(
  resizeEdges != null && dnd.current && store.isResizable(event) ? resizeEdges : [],
)
const buttonClass = $derived(clsx(extraClass, isGrabbed && 'bc-event-grabbed', isDraggable && 'bc-event-draggable'))
const accessibleName = $derived(time ? `${title}, ${time}` : title)

let clickTimer: ReturnType<typeof setTimeout> | null = null
onDestroy(() => { if (clickTimer !== null) clearTimeout(clickTimer) })

const select = () => { if (id != null) store.selectEvent({ id }) }
const primary = (e: MouseEvent | KeyboardEvent) => { select(); eventHandlers.click(event, e) }
const secondary = (e: MouseEvent | KeyboardEvent) => { select(); eventHandlers.doubleClick(event, e) }

function handleClick(e: MouseEvent) {
  if (e.detail === 0) return
  if (clickTimer !== null) return
  clickTimer = setTimeout(() => { clickTimer = null; primary(e) }, DOUBLE_CLICK_MS)
}

function handleDblClick(e: MouseEvent) {
  if (clickTimer !== null) { clearTimeout(clickTimer); clickTimer = null }
  secondary(e)
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); primary(e) }
  else if (e.key === 'F2') { e.preventDefault(); secondary(e) }
}
</script>

<button
  type="button"
  class={buttonClass}
  {style}
  data-bc-event={id == null ? '' : String(id)}
  aria-selected={isSelected}
  aria-grabbed={isGrabbed || undefined}
  aria-label={accessibleName || undefined}
  aria-keyshortcuts="Enter Space F2"
  aria-describedby={descriptionIds.event}
  onclick={handleClick}
  ondblclick={handleDblClick}
  onkeydown={handleKeydown}
  oncontextmenu={eventHandlers.hasRightClick ? (e) => eventHandlers.rightClick(event, e) : undefined}
  onauxclick={(e) => { if (e.button === 1 && eventHandlers.hasMiddleClick) eventHandlers.middleClick(event, e) }}
  onpointerdown={(e) => e.stopPropagation()}
>
  {@render children?.()}
  {#each edges as edge (edge)}
    <span class="bc-resize-handle bc-resize-handle-{edge}" data-bc-resize={edge} aria-hidden="true"></span>
  {/each}
</button>
