// packages/vue/src/DefaultMonthShowMore/DefaultMonthShowMore.vue
<script setup lang="ts" generic="TEvent = unknown">
import type { Component } from 'vue'
import EventButton from '../EventButton/EventButton.vue'
import Popover from '../Popover/Popover.vue'
import type { ShowMoreEvent } from '../components.type'

const props = defineProps<{
  count: number
  label: string
  day: string
  events: ReadonlyArray<ShowMoreEvent<TEvent>>
  eventSlot: Component
}>()
</script>

<template>
  <Popover placement="bottom-start" same-width class-name="bc-popover bc-show-more-popover">
    <template #trigger="{ setAnchor, popoverTarget, ariaHaspopup, ariaExpanded, ariaControls }">
      <button
        :ref="setAnchor"
        :popovertarget="popoverTarget"
        :aria-haspopup="ariaHaspopup"
        :aria-expanded="ariaExpanded"
        :aria-controls="ariaControls"
        type="button"
        class="bc-show-more"
      >{{ label }}</button>
    </template>
    <EventButton
      v-for="item in events"
      :key="item.key"
      class="bc-segment"
      :event="item.event"
      :title="item.title"
      :resize-edges="[]"
    >
      <component :is="props.eventSlot" :event="item.event" :title="item.title" />
    </EventButton>
  </Popover>
</template>

// packages/react/src/MonthView/components/DefaultMonthShowMore.component.tsx
import type { MonthShowMoreProps } from '../../components.type'
import { Popover } from '../../Popover'

/**
 * Default week overflow indicator: a `.bc-show-more` button that opens a
 * top-layer {@link Popover} listing the events that did not fit the week's row
 * limit. Replace via `components.month.showMore`.
 */
function DefaultMonthShowMore<TEvent>({ label, events }: MonthShowMoreProps<TEvent>) {
  return (
    <Popover
      placement="bottom-start"
      trigger={(triggerProps) => (
        <button {...triggerProps} type="button" className="bc-show-more">
          {label}
        </button>
      )}
    >
      <ul className="bc-popover-events">
        {events.map((item) => (
          <li key={item.key} className="bc-popover-event">
            {item.title}
          </li>
        ))}
      </ul>
    </Popover>
  )
}

export default DefaultMonthShowMore
