// packages/vue/src/Tooltip/Tooltip.vue
<script setup lang="ts">
import type { FloatingPlacement } from '@big-calendar/core/utils'
import { ref, shallowRef, useId, watch } from 'vue'
import type { ComponentPublicInstance } from 'vue'
import { useFloatingAnchor } from '../internal/useFloatingAnchor'

interface PopoverControl {
  showPopover?: () => void
  hidePopover?: () => void
}

defineProps<{
  label: string
  placement?: FloatingPlacement
}>()

const id = useId()
const open = ref(false)
const anchorRef = shallowRef<HTMLSpanElement | null>(null)
const tipRef = shallowRef<HTMLDivElement | null>(null)

function setAnchorRef(el: Element | ComponentPublicInstance | null): void {
  anchorRef.value = el as HTMLSpanElement | null
}

function setTipRef(el: Element | ComponentPublicInstance | null): void {
  tipRef.value = el as HTMLDivElement | null
}

function show(): void { open.value = true }
function hide(): void { open.value = false }
function toggle(): void { open.value = !open.value }

watch(open, (isOpen) => {
  const tip = tipRef.value as (HTMLDivElement & PopoverControl) | null
  if (!tip) return
  if (isOpen) {
    if (typeof tip.showPopover === 'function') tip.showPopover()
  } else {
    if (typeof tip.hidePopover === 'function') tip.hidePopover()
  }
})

useFloatingAnchor(open, anchorRef, tipRef)
</script>

<template>
  <span
    :ref="setAnchorRef"
    class="bc-tooltip-anchor"
    style="display: inline-flex"
    :aria-describedby="id"
    @pointerenter="show"
    @pointerleave="hide"
    @focus="show"
    @blur="hide"
    @click="toggle"
  >
    <slot />
    <div
      :ref="setTipRef"
      :id="id"
      role="tooltip"
      popover="manual"
      class="bc-tooltip"
    >
      {{ label }}
    </div>
  </span>
</template>

// packages/svelte/src/Tooltip/Tooltip.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { FloatingPlacement } from '@big-calendar/core/utils'
import { useFloatingAnchor } from '../internal/useFloatingAnchor.svelte'

let {
  label,
  placement,
  children,
}: {
  label: string
  placement?: FloatingPlacement
  children?: Snippet
} = $props()

const id = `bc-tip-${Math.random().toString(36).slice(2)}`
let open = $state(false)
let anchorEl: HTMLSpanElement | null = $state(null)
let tipEl: HTMLDivElement | null = $state(null)

function show() { open = true }
function hide() { open = false }
function toggle() { open = !open }

$effect(() => {
  const tip = tipEl as (HTMLDivElement & { showPopover?: () => void; hidePopover?: () => void }) | null
  if (!tip) return
  if (open) {
    tip.showPopover?.()
  } else {
    tip.hidePopover?.()
  }
})

useFloatingAnchor(() => open, () => anchorEl, () => tipEl, placement)
</script>

<span
  bind:this={anchorEl}
  class="bc-tooltip-anchor"
  style="display:inline-flex"
  aria-describedby={id}
  onpointerenter={show}
  onpointerleave={hide}
  onfocus={show}
  onblur={hide}
  onclick={toggle}
>
  {@render children?.()}
  <div
    bind:this={tipEl}
    {id}
    role="tooltip"
    popover="manual"
    class="bc-tooltip"
  >{label}</div>
</span>
