// packages/svelte/src/MonthView/MonthView.svelte
<script lang="ts" generics="TEvent = unknown">
import EventButton from '../EventButton/EventButton.svelte'
import { captureListeners } from '../internal/captureAction'
import { useMonthView } from '../useMonthView'

let rootEl: HTMLElement | null = $state(null)
let gridEl: HTMLElement | null = $state(null)

const mv = useMonthView<TEvent>(() => rootEl, () => gridEl)
const {
  grid,
  components: { Weekday, DateCell, EventSlot, ShowMore },
  drilldown,
  announcer,
  monthHeader,
  weekRow,
  slotsContainer,
  backgroundsContainer,
  eventsContainer,
  getDaySlotProps,
  getWeekSelectionBand,
  getWeekPreviewBand,
  getSegmentProps,
  getShowMoreCellProps,
} = mv

const rootHandlers = $derived(mv.getRootProps())
const gridProps = $derived(mv.getMonthGridProps())
</script>

{#if grid.current !== null}
  <div
    bind:this={rootEl}
    class={rootHandlers.class}
    onkeydown={rootHandlers.onKeydown}
    use:captureListeners={{ keydown: rootHandlers.onKeydownCapture, focus: rootHandlers.onFocusCapture }}
  >
    <div {...announcer}>{mv.announcement()}</div>

    <div {...monthHeader}>
      {#each grid.current.weekdays as weekday (weekday.day)}
        <svelte:component this={Weekday} day={weekday.day} long={weekday.long} short={weekday.short} />
      {/each}
    </div>

    <div
      bind:this={gridEl}
      class={gridProps.class}
      style={gridProps.style}
      onpointerdown={gridProps.onPointerdown}
      onkeydown={gridProps.onKeydown}
      use:captureListeners={{ focus: gridProps.onFocusCapture }}
    >
      {#each grid.current.weeks as week, weekIndex (week.key)}
        <div {...weekRow}>
          <div {...slotsContainer}>
            {#each week.days as cell, dayIndex (cell.day)}
              <div {...getDaySlotProps(cell, weekIndex, dayIndex)}></div>
            {/each}
          </div>

          <div {...backgroundsContainer}>
            {#each week.days as cell (cell.day)}
              <div class:bc-date-cell={true} class:bc-today={cell.isToday} class:bc-off-range={cell.isOffRange}>
                <svelte:component
                  this={DateCell}
                  day={cell.day}
                  label={cell.label}
                  isToday={cell.isToday}
                  isOffRange={cell.isOffRange}
                  onDrillDown={() => drilldown(cell.day)}
                />
              </div>
            {/each}
          </div>

          {#if getWeekSelectionBand(weekIndex) !== null}
            {@const band = getWeekSelectionBand(weekIndex)!}
            <div class={band.class} style={band.style}></div>
          {/if}

          {#if getWeekPreviewBand(week) !== null}
            {@const band = getWeekPreviewBand(week)!}
            <div class={band.class} style={band.style}></div>
          {/if}

          <div {...eventsContainer}>
            {#each week.segments as segment (segment.key)}
              {@const segProps = getSegmentProps(segment)}
              <EventButton
                class={segProps.class}
                style={segProps.style}
                event={segment.event}
                title={segment.title}
                resizeEdges={segProps.resizeEdges}
              >
                <svelte:component this={EventSlot} event={segment.event} title={segment.title} />
              </EventButton>
            {/each}

            {#each week.days as cell, dayIndex (`more-${cell.day}`)}
              {@const moreProps = getShowMoreCellProps(cell, dayIndex, week.moreRow)}
              {#if moreProps !== null}
                <div class={moreProps.class} style={moreProps.style}>
                  <svelte:component
                    this={ShowMore}
                    count={moreProps.count}
                    label={moreProps.label}
                    day={moreProps.day}
                    events={moreProps.events}
                    eventSlot={EventSlot}
                  />
                </div>
              {/if}
            {/each}
          </div>
        </div>
      {/each}
    </div>
  </div>
{/if}

// packages/vue/src/MonthView/MonthView.vue
<script setup lang="ts" generic="TEvent = unknown">
import EventButton from '../EventButton/EventButton.vue'
import { useMonthView } from '../useMonthView'

const {
  grid,
  components: { Weekday, DateCell, EventSlot, ShowMore },
  announcement,
  announcer,
  drilldown,
  root,
  monthHeader,
  monthGrid,
  weekRow,
  slotsContainer,
  backgroundsContainer,
  eventsContainer,
  getDaySlotProps,
  getWeekSelectionBand,
  getWeekPreviewBand,
  getSegmentProps,
  getShowMoreCellProps,
} = useMonthView<TEvent>()
</script>

<template>
  <div
    v-if="grid !== null"
    :ref="root.ref"
    :class="root.class"
    @keydown="root.onKeydown"
    @keydown.capture="root.onKeydownCapture"
    @focus.capture="root.onFocusCapture"
  >
    <div v-bind="announcer">{{ announcement }}</div>

    <div v-bind="monthHeader">
      <component
        v-for="weekday in grid.weekdays"
        :is="Weekday"
        :key="weekday.day"
        :day="weekday.day"
        :long="weekday.long"
        :short="weekday.short"
      />
    </div>

    <div
      :ref="monthGrid.ref"
      :class="monthGrid.class"
      :style="monthGrid.style"
      @pointerdown="monthGrid.onPointerdown"
      @keydown="monthGrid.onKeydown"
      @focus.capture="monthGrid.onFocusCapture"
    >
      <div
        v-for="(week, weekIndex) in grid.weeks"
        :key="week.key"
        v-bind="weekRow"
      >
        <!-- Hit-targets for slot selection -->
        <div v-bind="slotsContainer">
          <div
            v-for="(cell, dayIndex) in week.days"
            :key="cell.day"
            v-bind="getDaySlotProps(cell, weekIndex, dayIndex)"
          />
        </div>

        <!-- Date cell backgrounds -->
        <div v-bind="backgroundsContainer">
          <div
            v-for="cell in week.days"
            :key="cell.day"
            :class="['bc-date-cell', cell.isToday && 'bc-today', cell.isOffRange && 'bc-off-range']"
          >
            <component
              :is="DateCell"
              :day="cell.day"
              :label="cell.label"
              :is-today="cell.isToday"
              :is-off-range="cell.isOffRange"
              :on-drill-down="() => drilldown(cell.day)"
            />
          </div>
        </div>

        <!-- Selection band (stub until 10-8) -->
        <div
          v-if="getWeekSelectionBand(weekIndex) !== null"
          :class="getWeekSelectionBand(weekIndex)!.class"
          :style="getWeekSelectionBand(weekIndex)!.style"
        />
        <!-- Drag-preview band -->
        <div
          v-if="getWeekPreviewBand(week) !== null"
          :class="getWeekPreviewBand(week)!.class"
          :style="getWeekPreviewBand(week)!.style"
        />

        <!-- Event segments and overflow cells -->
        <div v-bind="eventsContainer">
          <EventButton
            v-for="segment in week.segments"
            :key="segment.key"
            :class="getSegmentProps(segment).class"
            :style="getSegmentProps(segment).style"
            :event="segment.event"
            :title="segment.title"
            :resize-edges="getSegmentProps(segment).resizeEdges"
          >
            <component :is="EventSlot" :event="segment.event" :title="segment.title" />
          </EventButton>

          <template v-for="(cell, dayIndex) in week.days" :key="`more-${cell.day}`">
            <template v-if="getShowMoreCellProps(cell, dayIndex, week.moreRow) !== null">
              <div
                :class="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.class"
                :style="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.style"
              >
                <component
                  :is="ShowMore"
                  :count="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.count"
                  :label="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.label"
                  :day="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.day"
                  :events="getShowMoreCellProps(cell, dayIndex, week.moreRow)!.events"
                  :event-slot="EventSlot"
                />
              </div>
            </template>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>
