// packages/vue/src/DefaultTimeDayHeading/DefaultTimeDayHeading.vue
<script setup lang="ts">
import clsx from 'clsx'
import { computed } from 'vue'
const props = defineProps<{
  day: string
  label: string
  isToday: boolean
  onDrillDown: () => void
}>()
const cls = computed(() => clsx('bc-day-heading', props.isToday && 'bc-today'))
</script>
<template>
  <button type="button" :class="cls" @click="onDrillDown">{{ label }}</button>
</template>

// packages/svelte/src/DefaultTimeDayHeading/DefaultTimeDayHeading.svelte
<script lang="ts">
import clsx from 'clsx'
let { label, isToday, onDrillDown }: { day: string; label: string; isToday: boolean; onDrillDown: () => void } = $props()
const cls = $derived(clsx('bc-day-heading', isToday && 'bc-today'))
</script>
<button type="button" class={cls} onclick={onDrillDown}>{label}</button>
