// packages/vue/src/Popover/Popover.vue
<script setup lang="ts">
import type { FloatingPlacement } from '@big-calendar/core/utils'
import { ref, shallowRef, useId } from 'vue'
import type { ComponentPublicInstance } from 'vue'
import { useFloatingAnchor } from '../internal/useFloatingAnchor'

interface PopoverToggleEvent extends Event {
  readonly newState: string
}

const {
  placement = 'bottom-start',
  className = 'bc-popover',
  sameWidth,
} = defineProps<{
  placement?: FloatingPlacement
  className?: string
  sameWidth?: boolean
}>()

defineSlots<{
  trigger(props: {
    setAnchor: (el: Element | ComponentPublicInstance | null) => void
    popoverTarget: string
    ariaHaspopup: 'dialog'
    ariaExpanded: boolean
    ariaControls: string
  }): unknown
  default(): unknown
}>()

const id = useId()
const open = ref(false)
const anchorRef = shallowRef<HTMLElement | null>(null)
const panelRef = shallowRef<HTMLDivElement | null>(null)

function setAnchor(el: Element | ComponentPublicInstance | null): void {
  anchorRef.value = el as HTMLElement | null
}

function setPanelRef(el: Element | ComponentPublicInstance | null): void {
  panelRef.value = el as HTMLDivElement | null
}

function handleToggle(event: Event): void {
  open.value = (event as PopoverToggleEvent).newState === 'open'
}

useFloatingAnchor(open, anchorRef, panelRef, placement, sameWidth)
</script>

<template>
  <slot
    name="trigger"
    :set-anchor="setAnchor"
    :popover-target="id"
    :aria-haspopup="'dialog'"
    :aria-expanded="open"
    :aria-controls="id"
  />
  <div
    :ref="setPanelRef"
    :id="id"
    popover="auto"
    :class="className"
    @toggle="handleToggle"
  >
    <slot v-if="open" />
  </div>
</template>

// packages/svelte/src/Popover/Popover.svelte
<script lang="ts">
import type { Snippet } from 'svelte'
import type { FloatingPlacement } from '@big-calendar/core/utils'
import { useFloatingAnchor } from '../internal/useFloatingAnchor.svelte'

interface TriggerSlotProps {
  bindAnchor: (node: HTMLElement) => { destroy: () => void }
  popoverTarget: string
  ariaHaspopup: 'dialog'
  ariaExpanded: boolean
  ariaControls: string
}

let {
  placement = 'bottom-start',
  className = 'bc-popover',
  sameWidth,
  trigger,
  children,
}: {
  placement?: FloatingPlacement
  className?: string
  sameWidth?: boolean
  trigger: Snippet<[TriggerSlotProps]>
  children?: Snippet
} = $props()

const id = `bc-pop-${Math.random().toString(36).slice(2)}`
let open = $state(false)
let anchorEl: HTMLElement | null = $state(null)
let panelEl: HTMLDivElement | null = $state(null)

function bindAnchor(node: HTMLElement) {
  anchorEl = node
  return { destroy() { anchorEl = null } }
}

function handleToggle(e: Event) {
  open = (e as Event & { newState: string }).newState === 'open'
}

useFloatingAnchor(
  () => open,
  () => anchorEl,
  () => panelEl,
  placement,
  sameWidth,
)
</script>

{@render trigger({ bindAnchor, popoverTarget: id, ariaHaspopup: 'dialog', ariaExpanded: open, ariaControls: id })}
<div
  bind:this={panelEl}
  {id}
  popover="auto"
  class={className}
  ontoggle={handleToggle}
>
  {#if open}
    {@render children?.()}
  {/if}
</div>
