// packages/react/src/TimeGridView/components/DefaultTimeDayHeading.component.tsx
import clsx from 'clsx'
import type { TimeDayHeadingProps } from '../../components.type'

/**
 * Default day column heading: a clickable label that drills into the day, with
 * the `bc-today` state class. Replace via `components.time.dayHeading`.
 */
function DefaultTimeDayHeading({ label, isToday, onDrillDown }: TimeDayHeadingProps) {
  const className = clsx('bc-day-heading', isToday && 'bc-today')
  return (
    <button type="button" className={className} onClick={onDrillDown}>
      {label}
    </button>
  )
}

export default DefaultTimeDayHeading

// packages/vue/src/DefaultTimeDayHeading/DefaultTimeDayHeading.vue
<script setup lang="ts">
import clsx from 'clsx'
import { computed } from 'vue'
const props = defineProps<{
  day: string
  label: string
  isToday: boolean
  onDrillDown: () => void
}>()
const cls = computed(() => clsx('bc-day-heading', props.isToday && 'bc-today'))
</script>
<template>
  <button type="button" :class="cls" @click="onDrillDown">{{ label }}</button>
</template>
