// packages/svelte/src/DefaultTimeShowMore/DefaultTimeShowMore.svelte
<script lang="ts" generics="TEvent = unknown">
import type { Component } from 'svelte'
import EventButton from '../EventButton/EventButton.svelte'
import Popover from '../Popover/Popover.svelte'
import type { ShowMoreEvent } from '../components.type'

let {
  count: _count,
  label,
  events,
  eventSlot: EventSlot,
}: {
  count: number
  label: string
  events: ReadonlyArray<ShowMoreEvent<TEvent>>
  eventSlot: Component
} = $props()
</script>

<Popover placement="bottom-start" sameWidth className="bc-popover bc-show-more-popover">
  {#snippet trigger({ bindAnchor, popoverTarget, ariaHaspopup, ariaExpanded, ariaControls })}
    <button
      use:bindAnchor
      popovertarget={popoverTarget}
      aria-haspopup={ariaHaspopup}
      aria-expanded={ariaExpanded}
      aria-controls={ariaControls}
      type="button"
      class="bc-show-more"
    >{label}</button>
  {/snippet}
  {#each events as item (item.key)}
    <EventButton class="bc-segment" event={item.event} title={item.title} resizeEdges={[]}>
      <svelte:component this={EventSlot} event={item.event} title={item.title} />
    </EventButton>
  {/each}
</Popover>

// packages/react/src/TimeGridView/components/DefaultTimeShowMore.component.tsx
import type { TimeShowMoreProps } from '../../components.type'
import { Popover } from '../../Popover'

/**
 * Default all-day overflow indicator: a `.bc-show-more` button that opens a
 * top-layer {@link Popover} listing the all-day events that did not fit the
 * row limit. Replace via `components.time.showMore`.
 */
function DefaultTimeShowMore<TEvent>({ label, events }: TimeShowMoreProps<TEvent>) {
  return (
    <Popover
      placement="bottom-start"
      trigger={(triggerProps) => (
        <button {...triggerProps} type="button" className="bc-show-more">
          {label}
        </button>
      )}
    >
      <ul className="bc-popover-events">
        {events.map((item) => (
          <li key={item.key} className="bc-popover-event">
            {item.title}
          </li>
        ))}
      </ul>
    </Popover>
  )
}

export default DefaultTimeShowMore
