// packages/vue/src/DefaultMonthDate/DefaultMonthDate.vue
<script setup lang="ts">
import clsx from 'clsx'
import { computed } from 'vue'
const props = defineProps<{
  day: string
  label: string
  isToday: boolean
  isOffRange: boolean
  onDrillDown: () => void
}>()
const cls = computed(() =>
  clsx('bc-date-cell', props.isToday && 'bc-today', props.isOffRange && 'bc-off-range'),
)
</script>
<template>
  <div :class="cls">
    <button type="button" class="bc-date-number" @click="onDrillDown">
      {{ label }}
    </button>
  </div>
</template>

// packages/react/src/DefaultMonthDate/DefaultMonthDate.component.tsx
import clsx from 'clsx'
import type { MonthDateProps } from '../components.type'

/**
 * Default day cell: a clickable date number that drills into the day. Carries
 * the `bc-today` / `bc-off-range` state classes. Replace via
 * `components.month.dateCell`.
 */
function DefaultMonthDate({ label, isToday, isOffRange, onDrillDown }: MonthDateProps) {
  const className = clsx('bc-date-cell', isToday && 'bc-today', isOffRange && 'bc-off-range')
  return (
    <div className={className}>
      <button type="button" className="bc-date-number" onClick={onDrillDown}>
        {label}
      </button>
    </div>
  )
}

export default DefaultMonthDate
