// packages/svelte/src/DefaultAgendaEvent/DefaultAgendaEvent.svelte
<script lang="ts" generics="TEvent = unknown">
import AgendaEventButton from '../AgendaEventButton/AgendaEventButton.svelte'
let { event, title, time }: { event: TEvent; title: string; time: string; allDay: boolean } = $props()
</script>
<div class="bc-agenda-row">
  <span class="bc-agenda-time">{time}</span>
  <AgendaEventButton {event} {title} />
</div>

// packages/react/src/AgendaView/components/DefaultAgendaEvent.component.tsx
import type { AgendaEventProps } from '../../components.type'

/** Default agenda event row: a time column and the event title. Replace via `components.agenda.event`. */
function DefaultAgendaEvent({ title, time }: AgendaEventProps<unknown>) {
  return (
    <div className="bc-agenda-row">
      <span className="bc-agenda-time">{time}</span>
      <span className="bc-event">
        <span className="bc-event-title">{title}</span>
      </span>
    </div>
  )
}

export default DefaultAgendaEvent
